name: Deploy React + Vite to Azure Storage Static Website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ecommerce-frontend
        run: npm ci

      - name: Build app
        working-directory: ecommerce-frontend
        run: npm run build



      - name: Upload to $web container
        run: |
          az storage blob upload-batch \
            --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} \
            --account-key ${{ secrets.STORAGE_ACCOUNT_KEY }} \
            --source ecommerce-frontend/dist \
            --destination '$web' \
            --overwrite

      - name: Show Website URL
        run: |
          echo "Website URL:"
          echo "https://${{ secrets.STORAGE_ACCOUNT_NAME }}.z13.web.core.windows.net/"